### ISSUE TITLE
not working on linux

### ISSUE THREAD

**Issue by kassindornelles** [xianfei/SysMocap#8] opened 2022-05-31 08:55 UTC
all the buttons in the app are not clickabe, and also a bunch of rendering issues
i'm using the RADV driver on linux (amd rx 560).

![image](https://user-images.githubusercontent.com/40970965/171134070-cd8e53b7-31dc-4b92-b51f-a2043b98d875.png)

i couldnt get any useful logs

**Comment by kassindornelles** [comment] 2022-05-31 08:55
unrealated issue: the UI it's in chinese by default

**Comment by kassindornelles** [comment] 2022-05-31 08:59
logs

```0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
1 info using npm@8.5.5
2 info using node@v18.2.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 3ms
10 timing config:load:file:/home/kassin/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 1ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 11ms
18 timing npm:load:configload Completed in 11ms
19 timing npm:load:setTitle Completed in 0ms
20 timing config:load:flatten Completed in 2ms
21 timing npm:load:display Completed in 4ms
22 verbose logfile /home/kassin/.npm/_logs/2022-05-31T08_51_39_164Z-debug-0.log
23 timing npm:load:logFile Completed in 4ms
24 timing npm:load:timers Completed in 0ms
25 timing npm:load:configScope Completed in 0ms
26 timing npm:load Completed in 20ms
27 timing command:run-script Completed in 4ms
28 timing command:start Completed in 7ms
29 verbose stack Error: ENOENT: no such file or directory, open '/home/kassin/package.json'
30 verbose cwd /home/kassin
31 verbose Linux 5.18.1-arch1-1
32 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
33 verbose node v18.2.0
34 verbose npm  v8.5.5
35 error code ENOENT
36 error syscall open
37 error path /home/kassin/package.json
38 error errno -2
39 error enoent ENOENT: no such file or directory, open '/home/kassin/package.json'
40 error enoent This is related to npm not being able to find a file.
40 error enoent
41 verbose exit -2
42 timing npm Completed in 132ms
43 verbose code -2
44 error A complete log of this run can be found in:
44 error     /home/kassin/.npm/_logs/2022-05-31T08_51_39_164Z-debug-0.log```

**Comment by xianfei** [comment] 2022-05-31 09:01
> unrealated issue: the UI it's in chinese by default

this issue is fixed on tag 0.5.0 in branch separate-mocap-and-render `window.navigator.language.split("-")[0] == "zh" ? "zh" : "en",`   you can try this branch.

**Comment by xianfei** [comment] 2022-05-31 09:07
I have only tested it on Ubuntu 22.04 with NVIDIA card. What is your operating system?

And I think you can try to open DevTools in the menu bar to see if there are any errors in DevTools console. There may be useful information here.

**Comment by EdLovecraft** [comment] 2022-05-31 09:40
![image](https://user-images.githubusercontent.com/40231164/171143885-302f1854-18ee-4313-8c36-937293d24d3a.png)

**Comment by xianfei** [comment] 2022-05-31 09:46
> ![image](https://user-images.githubusercontent.com/40231164/171143885-302f1854-18ee-4313-8c36-937293d24d3a.png)

I think it caused by too low version of electron. You can type `navigator.userAgent` in console and see your electron and chromium version.

**Comment by ga2mer** [comment] 2022-05-31 09:50
https://github.com/xianfei/SysMocap/blob/main/mainview/framework.html#L815
Seems to issue is here and `glRenderer` is undefined, if I remove this, everything works

**Comment by xianfei** [comment] 2022-05-31 09:54
> https://github.com/xianfei/SysMocap/blob/main/mainview/framework.html#L815 Seems to issue is here and `glRenderer` is undefined, if I remove this, everything works

It should be fixed by replacing `glRenderer.substr(7,glRenderer.length-8)` with `glRenderer?.substr(7,glRenderer.length-8)` in mainview/framework.html.

**Comment by Rewarp** [comment] 2022-06-11 09:19
I can confirm the fix

> > https://github.com/xianfei/SysMocap/blob/main/mainview/framework.html#L815 Seems to issue is here and `glRenderer` is undefined, if I remove this, everything works
> 
> It should be fixed by replacing `glRenderer.substr(7,glRenderer.length-8)` with `glRenderer?.substr(7,glRenderer.length-8)` in mainview/framework.html. Thank @ga2mer .

I can confirm this fix with a freshly cloned repo. Running on openSUSE Tumbleweed, image 20220608. The previous option 動作捕捉 was not working and now works! Thanks for the excellent work to make it cross platform and easy to deploy!

**Closed** 2022-11-08 11:57 UTC
Labels: bug
